mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: '123456'
  db_name: eladmin

pre_package: com.ccb.cloud.metadata.
base_page: com.hwr.common
title: wechat
path: /home/yuan/data/python/gen/